export const GITHUB_REPO_LOADING = 'GITHUB_REPO_LOADING';
export const GITHUB_REPO_SUCCESS = 'GITHUB_REPO_SUCCESS';
export const GITHUB_REPO_ERROR = 'GITHUB_REPO_ERROR';
export const GITHUB_REPO_RESET = 'GITHUB_REPO_RESET';

export const GITHUB_USER_LOADING = 'GITHUB_USER_LOADING';
export const GITHUB_USER_SUCCESS = 'GITHUB_USER_SUCCESS';
export const GITHUB_USER_ERROR = 'GITHUB_USER_ERROR';
export const GITHUB_USERS_SUCCESS = 'GITHUB_USERS_SUCCESS';
export const GITHUB_USER_RESET = 'GITHUB_USER_RESET';

export const STARGAZERS_LOADING = 'STARGAZERS_LOADING';
export const STARGAZERS_SUCCESS = 'STARGAZERS_SUCCESS';
export const STARGAZERS_ERROR = 'STARGAZERS_ERROR';
export const STARGAZERS_RESET = 'STARGAZERS_RESET';
